### ISSUE TITLE
Raphael not able to boot

### ISSUE THREAD

**Issue by graphiks** [edk2-porting/MU-SM8150Pkg#122]
I compiled edk2 myself for raphael, it shows windows 11 logo, then throws a "IRQL_NOT_LESS_OR_EQUAL" BSOD. How can i get logs for more troubleshooting?

**Comment by sunflower2333** [comment]
have u installed drivers?

**Comment by graphiks** [comment]
Right, i forgot. sorry.  But i cant install them , dism just throws a " error 87: Add-Driver command is unkown." I would highly appreciate if someone would help me in this or inject them for me? EDIT: I got them injected, now it boots.

**Comment by halal-beef** [comment]
@graphiks Btw we use driverupdater from the WOA-Project org to install the drivers instead of dism, I advise you to do the same

**Comment by graphiks** [comment]
Can you use it while in PE? Ive tried msm on another image but it doesnt detect my phone. Can you boot into msm or anything other than windows with this image?

**Comment by sunflower2333** [comment]
Yes it works ok here and it can boot linux too.


________________________________
发件人: graphik ***@***.***>
发送时间: 2023年10月10日星期二 下午8:06
收件人: woa-msmnile/msmnilePkg ***@***.***>
抄送: Kancy Joe ***@***.***>; Comment ***@***.***>
主题: Re: [woa-msmnile/msmnilePkg] Raphael not able to boot (Issue #122)


Can you use it while in PE? Ive tried msm on another image but it doesnt detect my phone. Can you boot into msm or anything other than windows with this image?

―

**Comment by graphiks** [comment]
Ok, this might be a bit of a stupid question but how do i boot in mass storage mode?

**Comment by sunflower2333** [comment]
how did you apply windows image?

Sunflower2333.
________________________________

**Comment by graphiks** [comment]
I made a winpe partition and put the efi files on there. Windows isnt installed currently
