### ISSUE TITLE
Oneplus CrashDump Error

### ISSUE THREAD

**Issue by sunflower2333** [edk2-porting/MU-SM8150Pkg#213]
On part of oneplus devices with OOS11 or OOS12, they may enconter CrashDumpMode while loading windows.

**Comment by NetuserPRO** [comment]
@sunflower2333 With OOS12 on guacamoleb, it loads Windows Boot Manager, but nothing and a reboot after when trying to boot windows.

**Comment by sunflower2333** [comment]
Find by ProNetUser:
  - This issue is casued by mismatch of XBL and EFI firmware used in our repo repo. currently finding out which binaries caused that. /:

**Comment by NetuserPRO** [comment]
@sunflower2333 why you keep writing my nickname incorrectly?

**Comment by sunflower2333** [comment]
sorry 
@NetuserPRO

**Comment by sunflower2333** [comment]
Fixed for hotdog at https://github.com/woa-msmnile/msmnilePkg/commit/376665502be886a85278ae6212d265a45450c256
