### ISSUE TITLE
Should be TARGET_RAM_SIZE here.

### ISSUE THREAD

**Issue by sunflower2333** [edk2-porting/MU-SM8150Pkg#29]
https://github.com/edk2-porting/MU-sm8150pkg/blob/f1279ab26899adee7e9f9d5766c9b99925c082fa/Platforms/SurfaceDuoPkg/SurfaceDuo.dsc#L98

**Comment by MollySophia** [comment]
Will add the fix to main branch after gus33000's rebase is done. Thanks.
Btw you can also add commits to this repo.
