### ISSUE TITLE
Confused on extracting xbl from samsung

### ISSUE THREAD

**Issue by 49b** [edk2-porting/MU-SM8150Pkg#30]
(I don't know where to ask about the [tutorial](https://renegade-project.org/#/en/sm8150pkg/tutorial/README) about porting edk2 to SM8150 in the website, so I asked here.)
I extracted the xbl from the BL....md5 file from the Samsung firmware, but opening it in 7-zip resulted in an error
So, I am going to extract xbl from the device, but I don't know which xbl I get:
`/dev/block/by-name/xbl`
`/dev/block/platform/soc/......ufshc/by-name/xbl`
(I found the xbl paths by running `find / | grep xbl` and seeing the last few lines.)
Can someone please answer this question? thanks.

**Comment by MollySophia** [comment]
These two paths are the same thing, as they are linked to the same block device.

**Comment by STUkh** [comment]
You don't really have to "open" it.

Open just 7zip from "start" panel. The go to path with file and when follow instruction - click "open #" over it
