### ISSUE TITLE
Crashdumpmode oos11 oneplus 7pro 

### ISSUE THREAD

**Issue by mohahack** [edk2-porting/MU-SM8150Pkg#301]
When I use the latest version of UEFI in the action menu of the OnePlus 7 Pro Oos11 (guacamole), I get an error CrashDumpMode

**Comment by mohahack** [comment]
When I use the latest version of UEFI in the action menu of the OnePlus 7 Pro Oos11 (guacamole), I get an error CrashDumpMode

**Comment by NetuserPRO** [comment]
#213

**Comment by arminask** [comment]
> When I use the latest version of UEFI in the action menu of the OnePlus 7 Pro Oos11 (guacamole), I get an error CrashDumpMode

Update to OOS12, and flash OOS11 devcfg, should boot then.

**Comment by sunflower2333** [comment]
Be patient, ProNetUser will update soon.
Btw honestly i do not suggest u using oos12.

Sunflower2333.
________________________________

**Comment by NetuserPRO** [comment]
https://github.com/NetuserPRO/msmnilePkg/actions/runs/9281629494 if no issues reported, will be pushed to upstream

**Comment by sunflower2333** [comment]
@NetuserPRO wait test result🙃

**Comment by NetuserPRO** [comment]
merged #302

**Comment by mohahack** [comment]
Yes it worked for me on guacamole oos11 now
