### ISSUE TITLE
edk2 unable to boot on vayu

### ISSUE THREAD

**Issue by halal-beef** [edk2-porting/MU-SM8150Pkg#32]
after building, i tried to boot the image and im met with loads of texts and then a prompt reboot into android, i have tried to change dtb and the CustomizedBinaries folder with up to date ones, but still no avail

heres the only picture of what was happening before crash / reboot (sadly not the clearest image)

![image](https://user-images.githubusercontent.com/78730004/193398185-9b9323b0-2956-4c99-8195-eb6b5daeb012.png)

**Comment by halal-beef** [comment]
last driver to load was haliommu

**Comment by degdag** [comment]
> last driver to load was haliommu

It's not the last driver loaded but it's PilDxe .
This is a known issue , still not fixed
You can comment it from DXE.inc

**Comment by halal-beef** [comment]
oops my bad, alright ill comment it out

**Comment by degdag** [comment]
> oops my bad, alright ill comment it out

However if you plan to use winpe , than USB will not work on pe even with a powered hub
I didn't tested surface duo guide but I guess you could try the guide if you plan to test the full windows

**Comment by halal-beef** [comment]
we are using another method for winpe, making a pe partition then installing pe to there

**Comment by degdag** [comment]
> we are using another method for winpe, making a pe partition then installing pe to there

Even if you boot to winpe you can't use mouse or keyboard over USB to deploy the full windows installation .
However as I told you . you can try surface duo installation guide if you want full windows installation

**Comment by halal-beef** [comment]
thanks for the warning atleast

**Comment by halal-beef** [comment]
tysm the efi now boots
