### ISSUE TITLE
Not sure whether to use 6 or 8GB RAM in `./build_uefi.sh` with 12GB RAM in phone 

### ISSUE THREAD

**Issue by 49b** [edk2-porting/MU-SM8150Pkg#40]
Hi, I would like to build for my own ported device, but the build script `./build_uefi.sh` only accepts 6GB or 8GB RAM, and Samsung Galaxy note 10 Plus has 12GB RAM, so should I use 6GB or 8GB of RAM for a phone with 12 GB? Thanks.

**Comment by sunflower2333** [comment]
Already tested 12GB. Haven't pushed yet.
