### ISSUE TITLE
CI FAILURE: build_platform_reference.yml@main

### ISSUE THREAD

**Issue by gus33000** [edk2-porting/MU-SM8150Pkg#411]
<html>
<body>

Error when evaluating 'strategy' for job 'build'. Project-Aloha/mu_aloha_platforms/.github/workflows/build_platform_reference.yml@main (Line: 38, Col: 17): Matrix vector 'target' does not contain any values
--

</body>
</html>

**Comment by sunflower2333** [comment]
Solved after pushing a reference device in palimapkg.
https://github.com/Project-Aloha/mu_aloha_platforms/actions/runs/11933039632
