### ISSUE TITLE
1

### ISSUE THREAD

**Issue by ghost** [edk2-porting/MU-SM8150Pkg#53]

**Comment by sunflower2333** [comment]
What are you doing ?

**Comment by sunflower2333** [comment]
Hi,
You play 3d games on it. But I do not know its performance. Maybe you need to test it yourself.
You can find guide on renegade project forum.
You can download UEFI firmware in GitHub action.
       You can find windows drivers in alula’s repo<https://github.com/alula>.
Sunflower2333

发件人: ***@***.***>
发送时间: 2022年11月9日 14:44
收件人: ***@***.***>
抄送: ***@***.***>
主题: [edk2-porting/MU-sm8150pkg] nubia mini 5g (Issue #53)


When nubia mini 5g had installed win11,can it play 3d games,like call of duty?Who have Guides for installing Windows on nubia mini 5g and the files needed(include uefi firmware)?I'm a beginer,can somone give me help?

―
