### ISSUE TITLE
How to compile UefiReader?

### ISSUE THREAD

**Issue by Android-Piepaint** [edk2-porting/MU-SM8150Pkg#71]
I looked your document called simple guide, then I found I need to compile an application called _UefiReader_. However, its repo doesn't gave me introduction about building it. How to compile it properly?

**Comment by Android-Piepaint** [comment]
<img width="1436" alt="Screenshot 2023-01-08 at 10 45 33 AM" src="https://user-images.githubusercontent.com/73344795/211178213-46af8c76-47da-4335-8747-ac22d6dabe14.png">
This is the repo itself

**Comment by qaz6750** [comment]
- It is obvious from the sln file that this needs to be compiled with Visual Studio
